blkparse_result_dir: "/home/data/iod/DB-data"
blkparse_result_format: "output"
parsing_result_dir: "/home/data/iod/DB-data/parsing"
parsing_result_format: ".parsing"
blkparse_raw_dir: "/home/data/iod/DB-data/raw"
delimiter: '\s+'
#program: '[rocksdb:low0]'
iotype: 'W' #any iotype that contain thw word. ex)W > W, WS, ...
names:
  [
    "dev<mjr,mnr>",
    "cpu",
    "seq_num",
    "timestamp",
    "pid",
    "event",
    "rwsb",
    "address",
    "+",
    "bs",
    "exec",
  ]
typedict:
  "dev<mjr,mnr>": str,
  "cpu": str, #np.int,
  "seq_num": str, #np.int64,
  "timestamp": str, #np.float64,
  "pid": str, #np.int64,
  "event": str,
  "rwsb": str,
  "address": str, #np.int64,
  "+": str,
  "bs": str, #np.int,
  "exec": str
