blkparse_result_dir: "/home/data/iod/replay/blktrace"
blkparse_result_format: "*.log"
parsing_result_dir: "/home/data/iod/replay/blktrace/formatted"
parsing_result_format: ".formatted"
blkparse_raw_dir: "/home/data/iod/replay/blktrace/raw"
delimiter: '\s+'
program: '[fio]'
names:
  [
    "dev<mjr,mnr>",
    "cpu",
    "seq_num",
    "timestamp",
    "pid",
    "event",
    "rwsb",
    "address",
    "+",
    "bs",
    "exec",
  ]
typedict:
  "dev<mjr,mnr>": str,
  "cpu": str, #np.int,
  "seq_num": str, #np.int64,
  "timestamp": str, #np.float64,
  "pid": str, #np.int64,
  "event": str,
  "rwsb": str,
  "address": str, #np.int64,
  "+": str,
  "bs": str, #np.int,
  "exec": str
